# Generated by Django 2.2.6 on 2019-11-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('hora', models.CharField(max_length=255)),
                ('participantes', models.CharField(max_length=255)),
            ],
        ),
    ]
