# Generated by Django 2.2.7 on 2019-11-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_eventos_organizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='organizador',
            field=models.CharField(max_length=255),
        ),
    ]
