# Generated by Django 2.2.6 on 2019-10-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='idade',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
