# Generated by Django 2.2.6 on 2019-11-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_colaborador_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='confirmEmail',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='confirmSenha',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='senha',
        ),
    ]
