# Generated by Django 2.2.6 on 2019-11-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0003_auto_20191104_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
