# Generated by Django 2.2.6 on 2019-11-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20191104_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='telefone',
            new_name='genero',
        ),
    ]
