# Generated by Django 2.2.6 on 2019-11-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_eventos_organizador'),
        ('usuario', '0003_auto_20191107_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='esporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Eventos'),
        ),
    ]
